# Generated by Django 5.0 on 2023-12-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ingredientes', models.CharField(max_length=300, verbose_name='Ingredientes')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Preparacion')),
            ],
        ),
    ]
